### ISSUE TITLE
Review sleep and hydration classes

### ISSUE THREAD

**Issue by jordy1611** [relyt4me/RefactorTractor-FitLit#13]
* Review sleep class
* Review hydration class

**Comment by relyt4me** [comment]
Hydration:
  - Constructor takes in a data group which are objects with userID(which does repeat) date(increments up) and numOunces (50 users/100 days)
  - calculateAverageOunces takes in a user Id and gives back the average of ounces/day, by first getting the all objects for one user, then averaging
  - calculateDailyOunces takes in id and date and returns the ounces where both of those match
  - calculateFirstWeekOunces takes in an instance of a class UserRepo and the id it then returns an array of strings corresponding to users and the first week total ounces
  - calculateRandomeWeekOunces same as above but also takes in a date and then grabs the date from that week (unsure if works as intended)

**Comment by relyt4me** [comment]
Sleep:
  * Constructor takes in sleepData which is an array of userID/date/hoursSlept/sleepQuality and sets that to its only property
  * calculateAverageSleep takes in an id gets the full list of sleep Data for that user then returns an average based on that users sleep hours
  * calculateAverageSleepQuality also takes in an id and as before uses the filter to get a single users data then returns an average based on the sleepQuality
  * calculateDailySleepQuality takes in an id and a date to give back a single quality refrencing that user and that date
  * calculateWeekSleep takes in a date, id, and userRepo instance, The userRepo gives an array which is a week of data for a user and then returns an array of strings that are the date with the sleepHours
  * calculateWeeksSleepQuality does the same as above but with quality
  * calculateAllUserSleepQuality takes in nothing but gives an total average for all of the sleepQuality for all users and all days
  * determineBestSleepers takes in a date and a userRepo instance then uses the userRepo to get a group of data isolated for a week and also just the sleepQuality for that week,  It then looks at they keys for that sleepQuality data to return a (group of users) or single user? with high sleepQuality
  * determinSleepWinnerForWeek takes in a date and a userRepo instance (no test) it thencreates a timleine and some(combineRankedUserIDsAndAverageData) passing that into the helper function that gets a winner.
  * determineSleepHoursWinnerForDay uses similar functionality to get a winner name for the sleep hours.
